config/routes.rb
Badado::Application.routes.draw do
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :items
  
  root :to => "home#index" 
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_ancestry
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def not_authenticated
    redirect_to login_url, :alert => "First login to access this page."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :require_login
  
  # GET /items
  # GET /items.json
  def index
    @items = Item.scoped

      respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new(:parent_id => params[:parent_id], :user_id => params[:user_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_path, :notice => 'Item was successfully created.' }
        format.json { render :json => items_path, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, :notice => 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def nested_items(items)
  items.map do |item, sub_items|
    render(item) + content_tag(:div, nested_items(sub_items), :class => "nested_item")
  end.join.html_safe
end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%h1 Home#index
= link_to "Items", items_path

app/views/items/_form.html.haml
= form_for(@item) do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= pluralize(@item.errors.count, "error")
      prohibited this item from being saved:
      
      %ul
        - @item.errors.full_messages.each do |msg|
          = msg
          
  = f.hidden_field :parent_id
  = f.hidden_field :user_id
    
  .field
    = f.label :content
    %br
    = f.text_field :content

  .actions= f.submit

app/views/items/_item.html.haml
.item
  = item.ancestry
  = link_to 'New task', new_item_path(:parent_id => item, :user_id => current_user)
  = link_to 'Show', item
  = link_to 'Edit', edit_item_path(item)
  = link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete

app/views/items/edit.html.haml
%h1Editing item

= render 'form'

= link_to 'Show', @item
= link_to 'Back', items_path

app/views/items/index.html.haml
%h1 Listing items
%p#notice= notice

= nested_items @items.arrange(:order => :created_at)

= link_to 'New List', new_item_path(:user_id => current_user)
= link_to 'On main', root_path

app/views/items/new.html.haml
%h1 New item

= render @item.parent if @item.parent 

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice

%p
  %b User
  = @item.user_id
  
%p
  %b Content 
  = @item.content
  
%p
  %b Checked
  = @item.checked

%p
  %b Order
  = @item.order


= link_to 'Edit', edit_item_path(@item)
= link_to 'Back', items_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Badado
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags 
  %body
    
  -if current_user
    Logged in as
    = current_user.email
    = link_to "Log out", logout_path
  -else
    = link_to "Sign up", signup_path
    = link_to "log in", login_path

  = yield

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>